/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TrainsRouteImport } from './routes/trains'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ScamsRouteImport } from './routes/scams'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as MapRouteImport } from './routes/map'
import { Route as LuggageRouteImport } from './routes/luggage'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AltRoutesRouteImport } from './routes/alt-routes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIndexRouteImport } from './routes/book/index'
import { Route as StopIdRouteImport } from './routes/stop.$id'
import { Route as BookIdRouteImport } from './routes/book/$id'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsRoute = TrainsRouteImport.update({
  id: '/trains',
  path: '/trains',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamsRoute = ScamsRouteImport.update({
  id: '/scams',
  path: '/scams',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LuggageRoute = LuggageRouteImport.update({
  id: '/luggage',
  path: '/luggage',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AltRoutesRoute = AltRoutesRouteImport.update({
  id: '/alt-routes',
  path: '/alt-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const StopIdRoute = StopIdRouteImport.update({
  id: '/stop/$id',
  path: '/stop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alt-routes': typeof AltRoutesRoute
  '/calendar': typeof CalendarRoute
  '/documents': typeof DocumentsRoute
  '/flights': typeof FlightsRoute
  '/guides': typeof GuidesRoute
  '/itinerary': typeof ItineraryRoute
  '/luggage': typeof LuggageRoute
  '/map': typeof MapRoute
  '/money': typeof MoneyRoute
  '/scams': typeof ScamsRoute
  '/timeline': typeof TimelineRoute
  '/trains': typeof TrainsRoute
  '/transport': typeof TransportRoute
  '/book/$id': typeof BookIdRoute
  '/stop/$id': typeof StopIdRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alt-routes': typeof AltRoutesRoute
  '/calendar': typeof CalendarRoute
  '/documents': typeof DocumentsRoute
  '/flights': typeof FlightsRoute
  '/guides': typeof GuidesRoute
  '/itinerary': typeof ItineraryRoute
  '/luggage': typeof LuggageRoute
  '/map': typeof MapRoute
  '/money': typeof MoneyRoute
  '/scams': typeof ScamsRoute
  '/timeline': typeof TimelineRoute
  '/trains': typeof TrainsRoute
  '/transport': typeof TransportRoute
  '/book/$id': typeof BookIdRoute
  '/stop/$id': typeof StopIdRoute
  '/book': typeof BookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alt-routes': typeof AltRoutesRoute
  '/calendar': typeof CalendarRoute
  '/documents': typeof DocumentsRoute
  '/flights': typeof FlightsRoute
  '/guides': typeof GuidesRoute
  '/itinerary': typeof ItineraryRoute
  '/luggage': typeof LuggageRoute
  '/map': typeof MapRoute
  '/money': typeof MoneyRoute
  '/scams': typeof ScamsRoute
  '/timeline': typeof TimelineRoute
  '/trains': typeof TrainsRoute
  '/transport': typeof TransportRoute
  '/book/$id': typeof BookIdRoute
  '/stop/$id': typeof StopIdRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alt-routes'
    | '/calendar'
    | '/documents'
    | '/flights'
    | '/guides'
    | '/itinerary'
    | '/luggage'
    | '/map'
    | '/money'
    | '/scams'
    | '/timeline'
    | '/trains'
    | '/transport'
    | '/book/$id'
    | '/stop/$id'
    | '/book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alt-routes'
    | '/calendar'
    | '/documents'
    | '/flights'
    | '/guides'
    | '/itinerary'
    | '/luggage'
    | '/map'
    | '/money'
    | '/scams'
    | '/timeline'
    | '/trains'
    | '/transport'
    | '/book/$id'
    | '/stop/$id'
    | '/book'
  id:
    | '__root__'
    | '/'
    | '/alt-routes'
    | '/calendar'
    | '/documents'
    | '/flights'
    | '/guides'
    | '/itinerary'
    | '/luggage'
    | '/map'
    | '/money'
    | '/scams'
    | '/timeline'
    | '/trains'
    | '/transport'
    | '/book/$id'
    | '/stop/$id'
    | '/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AltRoutesRoute: typeof AltRoutesRoute
  CalendarRoute: typeof CalendarRoute
  DocumentsRoute: typeof DocumentsRoute
  FlightsRoute: typeof FlightsRoute
  GuidesRoute: typeof GuidesRoute
  ItineraryRoute: typeof ItineraryRoute
  LuggageRoute: typeof LuggageRoute
  MapRoute: typeof MapRoute
  MoneyRoute: typeof MoneyRoute
  ScamsRoute: typeof ScamsRoute
  TimelineRoute: typeof TimelineRoute
  TrainsRoute: typeof TrainsRoute
  TransportRoute: typeof TransportRoute
  BookIdRoute: typeof BookIdRoute
  StopIdRoute: typeof StopIdRoute
  BookIndexRoute: typeof BookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains': {
      id: '/trains'
      path: '/trains'
      fullPath: '/trains'
      preLoaderRoute: typeof TrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scams': {
      id: '/scams'
      path: '/scams'
      fullPath: '/scams'
      preLoaderRoute: typeof ScamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luggage': {
      id: '/luggage'
      path: '/luggage'
      fullPath: '/luggage'
      preLoaderRoute: typeof LuggageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alt-routes': {
      id: '/alt-routes'
      path: '/alt-routes'
      fullPath: '/alt-routes'
      preLoaderRoute: typeof AltRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop/$id': {
      id: '/stop/$id'
      path: '/stop/$id'
      fullPath: '/stop/$id'
      preLoaderRoute: typeof StopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AltRoutesRoute: AltRoutesRoute,
  CalendarRoute: CalendarRoute,
  DocumentsRoute: DocumentsRoute,
  FlightsRoute: FlightsRoute,
  GuidesRoute: GuidesRoute,
  ItineraryRoute: ItineraryRoute,
  LuggageRoute: LuggageRoute,
  MapRoute: MapRoute,
  MoneyRoute: MoneyRoute,
  ScamsRoute: ScamsRoute,
  TimelineRoute: TimelineRoute,
  TrainsRoute: TrainsRoute,
  TransportRoute: TransportRoute,
  BookIdRoute: BookIdRoute,
  StopIdRoute: StopIdRoute,
  BookIndexRoute: BookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
